items: ["5050630615711"]
request_delay: 2 # A delay in seconds between HTTP GET calls
store_ids: [91, 89, 3054, 342, 152, 252, 206, 187, 113, 75] # Specific store IDs, by default not set (will check all stores), add [1, 2] to check stock for stores with IDs 1 and 2
proceed_prompt_enabled: False # Set to true if you wish to enter either y or n to proceed with the stock check.
send_email_enabled: False # Set to true if you wish to send the store stock check results to email
email: # Email address that will be used to send the message, e.g. email@foo.com
email_pass: # Password for the email account
to_email: # Email address to which the report will be sent, e.g. to_email@bar.com
smtp_host: # SMTP server host, e.q. mail.bar.com
smtp_port: # SMTP server port, e.g. 587